apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrower-notifications
  labels:
    app: borrower-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrower-notifications
  template:
    metadata:
      labels:
        app: borrower-notifications
    spec:
      containers:
      - name: borrower-notifications
        image: borrower-notifications:latest
        imagePullPolicy: Never
        env:
        - name: CASSANDRA_HOSTS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: cassandra-hosts
        - name: CASSANDRA_KEYSPACE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: cassandra-keyspace
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: kafka-brokers
---
apiVersion: v1
kind: Service
metadata:
  name: borrower-notifications
spec:
  selector:
    app: borrower-notifications
  ports:
  - port: 50052
    targetPort: 50052
